language: csharp
mono: none
dotnet: 3.1.200
script:
- dotnet restore
- dotnet build

before_deploy:
- mkdir Release
# Windows x64
- dotnet publish -c Release -r win-x64 /p:PublishSingleFile=true
- zip -j Release/win64.zip bin/Release/netcoreapp3.1/win-x64/publish/*
# Windows x86# Windows x86
- dotnet publish -c Release -r win-x86 /p:PublishSingleFile=true
- zip -j Release/win86.zip bin/Release/netcoreapp3.1/win-x86/publish/*
# Linux x64
- dotnet publish -c Release -r linux-x64 /p:PublishSingleFile=true
- zip -j Release/linux64.zip bin/Release/netcoreapp3.1/linux-x64/publish/*
# OSX x64
- dotnet publish -c Release -r osx-x64 /p:PublishSingleFile=true
- zip -j Release/osxx64.zip bin/Release/netcoreapp3.1/osx-x64/publish/*
# Git tag config
- git config --local user.name "Robert MacLean"
- git config --local user.email "robert@sadev.co.za"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key:
    secure: Q0p/L10JhU3g1cVfKoT09SnGMwJuIql1ofgoIf9wroyQ4+A5bQtzmM+6+Gh//px7Emn40w/ciVRUZvECyKf0eGWOm8pIf7QNHdZXv0fLj3fA5TMvRtBofBMto7zR+2uF0foLWCI1NarizlJCpB5KPtRh5nJ6s1THXrkGCzIXVnSGW2ntuZLEP+zUBh8zJddOi4LHL7kLJ1grN/XCmVKVXqHSdGapM2fj+rYsEVUpHZmoqs9exfHv+62zSSK+tR1u6tpRSYrVjCdccmdBE7WPw+IZpzorTRgHnIDsxXEMUNns+RBiKQkZ/LA2s3llz1hQoa+IRuwhB7CcTw2iHBewKy3Yqmm2DGmRqKBddHoNRjBN7z75jBXFsxgj1v+bIOLl7EpegPqNXblmXnXQmA5R/ST2Fn+9sYkSnP6foTiPJOu54EM/53rKtmptlJxnE7n/tZlRevLp5sWly54+RURKyBPhfcSbvhTz+ljvnErCfeOafahFxc3u6GPL3Nahp7j5K+o9VLGAegx1pNjraKmIvELxX+fxCJJ70P0mFx7a1j/+eHriabPk2TrgfLp9Op5JtSGPGdQa1XdLS7bCDIjk2whxpcppID7Xv+iYpQcua+BriUtZALG8s7dv/9guHWI/En29kcPHrHdiTbDTq7qd12rWOLOMiZjpYP5ZiAdd9EI=
  file_glob: true
  file: Release/*
  on:
    repo: rmaclean/twot
  skip_cleanup: true
  prerelease: true


