#!/bin/bash
rm -rf bin
rm -rf Release
mkdir Release

# Windows x64
dotnet.exe publish -c Release -r win-x64 /p:PublishSingleFile=true

zip -j Release/win64.zip bin/Release/netcoreapp3.1/win-x64/publish/*

# Windows x86
dotnet.exe publish -c Release -r win-x86 /p:PublishSingleFile=true

zip -j Release/win86.zip bin/Release/netcoreapp3.1/win-x86/publish/*

# Linux x64
dotnet.exe publish -c Release -r linux-x64 /p:PublishSingleFile=true

zip -j Release/linux64.zip bin/Release/netcoreapp3.1/linux-x64/publish/*

# OSX x64
dotnet.exe publish -c Release -r osx-x64 /p:PublishSingleFile=true

zip -j Release/osxx64.zip bin/Release/netcoreapp3.1/osx-x64/publish/*